version: "3.7"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: clay
      MYSQL_USER: clay
      MYSQL_PASSWORD: clay
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13306:3306"
    volumes:
      - "db-data:/var/lib/mysql"


volumes:
  db-data:
